[versions]
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
